# Before the practical session {#before}

Welcome to the practical session on R and RStudio. In this session we will look at why you want to use R and RStudio and how to get started.

Ideally, you'd complete a few things before the practical session: Watch the introductory video, get R and RStudio installed on your machine and get a brief overview of RStudio.

In the practical session we will then be able to focus on reading in some data, doing a bit of data manipulation, visualising data, complete some simple stats and use RMarkdown for writing up a report.

### Watch the introductory video (~20 minutes)
In this video I talk you through what we will be doing in the practical session and why. I also introduce various resources to get you started. You can download the slides of the presentation (with clickable urls) below.

* [**Introductory video**](https://estream.lancaster.ac.uk/View.aspx?id=68738~5t~O0DtRzCI6D&code=x4~a2uelROUQk8fQsjzPSgwCUMEBUAgsPVxFrb7BVlZALvBra6em7UxLd&ax=7R~bouVUlLrTqP3h5) - [slides](files/practicalSession_R_RStudio_overview.pdf)

### Getting started
Go to the [**Rladies - Sydney 'RYouWithMe' website**](https://rladiessydney.org/courses/ryouwithme/01-basicbasics-0/) and complete these following units:

1. BasicBasics 1: Installing R and RStudio + tour of RStudio (~20 minutes)
2. BasicBasics 2 Packages (~15 minutes)
3. BasicBasics 3: Getting data into RStudio (20 minutes)

4. CleanItUp 1: A start with data manipulation (~30 minutes) - OPTIONAL
